# Testing Environment Supabase Configuration
# This uses different ports to run alongside the development instance

project_id = "Helprs_V1_Testing"

[api]
enabled = true
port = 54331
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[api.tls]
enabled = false

[db]
port = 54332
shadow_port = 54330
major_version = 17

[db.pooler]
enabled = false
port = 54339
pool_mode = "transaction"
default_pool_size = 20
max_client_conn = 100

[db.migrations]
enabled = true
schema_paths = []

[db.seed]
enabled = true
sql_paths = ["../supabase/seed.sql"]

[realtime]
enabled = true

[studio]
enabled = true
port = 54333
api_url = "http://127.0.0.1"

[inbucket]
enabled = true
port = 54334

[storage]
enabled = true
file_size_limit = "50MiB"

[auth]
enabled = true
site_url = "http://127.0.0.1:3001"
additional_redirect_urls = ["https://127.0.0.1:3001"]
jwt_expiry = 3600
enable_refresh_token_rotation = true
refresh_token_reuse_interval = 10
enable_signup = true
enable_anonymous_sign_ins = false

[auth.email]
enable_signup = true
enable_confirmations = false

[auth.sms]
enabled = false

[edge_runtime]
enabled = true
policy = "per_worker"
inspector_port = 8084
deno_version = 2

[analytics]
enabled = true
port = 54337
backend = "postgres"

